import { generateMapFor } from "../game/mapRequest";
import type { GeneratedMap, MapRequest } from "../game/mapRequest";
import { readMapWorkerResponse } from "./mapWorkerProtocol";
import type { MapWorkerRequest } from "./mapWorkerProtocol";

/**
 * Posts one message to a map worker and resolves with the data it posts
 * back, or rejects if the worker cannot start or crashes. See
 * `createMapWorkerRunner` for the real one.
 */
export type RunMapWorker = (message: MapWorkerRequest) => Promise<unknown>;

/**
 * The map for `request`, generated by `runWorker` so the main thread stays
 * responsive (#124). With no worker (`undefined`, where workers are
 * unavailable), or one that fails, the map is generated here on the main
 * thread instead: the same pure generator either way, so the same map.
 */
export async function generateMapOffThread(
  request: MapRequest,
  runWorker: RunMapWorker | undefined
): Promise<GeneratedMap> {
  if (!runWorker) return onMainThread(request);
  try {
    const cells = readMapWorkerResponse(await runWorker({ request }));
    if (cells) return { ...request, cells };
    console.warn("The map worker could not generate the map; generating it on the main thread.");
  } catch (error) {
    console.warn("The map worker failed; generating the map on the main thread.", error);
  }
  return onMainThread(request);
}

function onMainThread(request: MapRequest): GeneratedMap {
  return { ...request, cells: generateMapFor(request) };
}
